require:
  # - rubocop-jekyll
  - rubocop-md
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

# inherit_gem:
#   rubocop-jekyll: .rubocop.yml

AllCops:
  Exclude:
    - demo/_site/**/*
    - binstub/**/*
    - vendor/**/*
    - Gemfile*
  NewCops: enable

Gemspec/DeprecatedAttributeAssignment:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Layout/InitialIndentation:
  Exclude:
    - README.md

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table
  Exclude:
    - jekyll_basename_dirname.gemspec

Layout/LineLength:
  Max: 150

Metrics/AbcSize:
  Max: 45

Lint/RedundantCopDisableDirective:
  Exclude:
    - jekyll_basename_dirname.gemspec

Metrics/BlockLength:
  Exclude:
    - jekyll_basename_dirname.gemspec
    - spec/**/*

Metrics/ClassLength:
  Exclude:
    - spec/**/*
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/MethodLength:
  Max: 40

Metrics/PerceivedComplexity:
  Max: 15

Naming/FileName:
  Exclude:
    - Rakefile

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 15

Style/CommandLiteral:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringConcatenation:
  Exclude:
    - spec/**/*

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
